### ISSUE TITLE
Manual Corporativo

### ISSUE THREAD

**Issue by ajsb85** [difesaonline/press-kit#1]

**Comment by IXGD** [comment]
Diseño de Manual Corporativo

**Comment by IXGD** [comment]
Hola @ajsb85  te dejo el pdf de lo trabajado hasta ahora.
[Manual Corporativo difesa.pdf](https://github.com/difesaonline/press-kit/files/13382902/Manual.Corporativo.difesa.pdf)

**Comment by IXGD** [comment]
Hola @ajsb85 el Manual Corporativo completo está en la carpeta press-kit, y toda la papelería también. Un saludo.
[Manual Corporativo difesa.pdf](https://github.com/difesaonline/press-kit/files/13394927/Manual.Corporativo.difesa.pdf)

**Comment by IXGD** [comment]
@ajsb85 cierro issues
