### ISSUE TITLE
Logotype

### ISSUE THREAD

**Issue by ajsb85** [difesaonline/press-kit#2]

**Comment by IXGD** [comment]
Diseño de logotipo

**Comment by IXGD** [comment]
Hola @ajsb85 , he creado una carpeta para compartir el logo pero no se si la podrás ver porque no la he podido enlazar bien.
Te dejo por aquí el logo y voy a crear el imagotipo.
![Logo difesa](https://github.com/difesaonline/press-kit/assets/150062070/be983e6a-851f-4b1c-a774-831db94fe9dc)

**Comment by IXGD** [comment]
Hola @ajsb85 te presento el imagotipo.
@
![Imagotipo difesa](https://github.com/difesaonline/press-kit/assets/150062070/6ff8c260-1db8-40e7-bc14-ae5e7900f492)

**Comment by IXGD** [comment]
Hola @ajsb85 ya está el logotipo vectorizado, todo lo trabajado está en el press-kit. Queda vectorizar el imagotipo y acabar el manual.
![Logo difesa vectorizado](https://github.com/difesaonline/press-kit/assets/150062070/ef3e841d-594d-4435-967b-bfd9ad0203c4)

**Comment by IXGD** [comment]
Hola @ajsb85 tambien te adjunto por aquí el imagotipo vectorizado. Los originales (AI) están en la carpeta press-kit. Un saludo.
![imagotipo vectorizado](https://github.com/difesaonline/press-kit/assets/150062070/6ff05b0c-1770-4edd-846a-1d4c3453df6b)

**Comment by IXGD** [comment]
@ajsb85 cierro issues
